### ISSUE TITLE
Can't call the emergency number

### ISSUE THREAD

**Issue by tunamert0** [SimpleMobileTools/Simple-Dialer#563] opened 2023-03-24 01:10 UTC
Android version: 11 and 12
App version: 5.17.x
Issue: I cannot call my country emergency number 112 or 911. I have experienced it when I was in an **_Emergency_**. It needs an immediate fix.

**Comment by Aga-C** [comment] 2023-03-24 07:54
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/158.

**Closed** 2023-03-24 10:22 UTC
