### ISSUE TITLE
Unable to switch back to Bluetooth headset audio

### ISSUE THREAD

**Issue by lordfolken** [SimpleMobileTools/Simple-Dialer#161] opened 2021-02-18 12:38 UTC
Hello

First of all great App!

In the call in progress screen I can change audio between speaker and phone. If I'm connected via Bluetooth it will switch to speaker as expected. However hitting it again will switch to the smartphone handset not to back to the Bluetooth audio connection.

Would it be possible to change the speaker icon to a dropdown list and support more than two audio destinations?

**Comment by tibbi** [comment] 2021-02-18 13:43
duplicate of #96

**Closed by tibbi** 2021-02-18 13:43 UTC
