### ISSUE TITLE
Misleading hands-free calling symbol

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Dialer#32] opened 2020-05-23 17:22 UTC
In the call view, there is a loudspeaker symbol. On click it toggles to a strike-through loudspeaker symbol. This is misleading a bit. For comparison, when toggling the microphone, it will be on (normal symbol) or off (struck symbol). As far as I understand, the loudspeaker symbol should toggle between the ear speaker (when holding the phone to the ear while calling) and the other speaker (*loudspeaker*) when using hands-free calling.

The "official" phone app uses a more consistent UI, toggling the button but not striking through the speaker symbol.

Version info:
5.2.0

**Comment by tibbi** [comment] 2020-05-23 17:40
there is no hands-free support yet, it just toggles between the loud speaker and the casual device one

**Comment by tibbi** [comment] 2020-05-23 17:41
duplicate of #31

**Closed by tibbi** 2020-05-23 17:41 UTC

**Comment by platinorum** [comment] 2022-02-27 19:23
It's no duplicate of #31 and I think that the mute and loudspeaker buttons are confusing too. I'd find it better if the button would show up highlighted instead of changing to an other icon to make it clear!
