### ISSUE TITLE
Feature Request - Option to display all calls with certain number/contact

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [SimpleMobileTools/Simple-Dialer#459] opened 2022-10-07 03:17 UTC
It might be useful to add a feature to display the time and date of all the past calls with a specific contact or number (the feature would be nice to have for numbers that are not stored as a contact, specifically for spam calls), similar to how subsequent calls from the same contact are grouped by default. An option in the vertical ellipsis menu could be added named something like "Show Call History".

Thanks!

**Comment by Aga-C** [comment] 2022-10-07 09:06
Looks the same as https://github.com/SimpleMobileTools/Simple-Dialer/issues/380.

**Comment by tibbi** [comment] 2022-10-07 09:19
right thanks, duplicate of #380

**Closed by tibbi** 2022-10-07 09:19 UTC
Labels: feature request

**Comment by shrimprugbysnowowl** [comment] 2022-10-07 12:13
Agreed, yes, duplicate issue. I read #380 - besides the guy being fairly rude, it's not clear to me why the issue was closed. Respectfully, can I ask why this wouldn't be reasonable or useful enough to consider incorporating? I understand all feature requests cannot be accommodated because your time is limited.
