### ISSUE TITLE
Screen doesn't unlock when receiving call

### ISSUE THREAD

**Issue by tryfon** [SimpleMobileTools/Simple-Dialer#323] opened 2022-03-23 10:56 UTC
I am using Simple Dialer v5.11.5 on a Xiaomi Note 9 Pro with MIUI 12.5.7.0 (Android 11) and when I receive a call the screen doesn't turn on or unlock and remains turned off. I have to unlock the screen and then slide down the top notification bar to answer the call. I do have the Display Over Other Apps permission given to Simple Dialer.
This is obviously a breaking bug for the application. Is there a known workaround?

**Comment by tibbi** [comment] 2022-03-23 11:16
duplicate of #188

**Closed by tibbi** 2022-03-23 11:16 UTC

**Comment by tryfon** [comment] 2022-03-23 12:09
Not exactly duplicate. In my case I fixed it by going to Settings->Permissions->Other Permissions->Dialer and enabling "Show on Lock screen", "Display pop-up windows while running in the background" and "Display pop-up window" permissions. It was probably the first one that did the trick. I guess the App should check and request these permissions (at least the first one) every time it is used. It had nothing to do with "Duraspeed" as in ticket #188

**Comment by tibbi** [comment] 2022-03-23 17:23
such issues are sadly device and system specific, we cannot write any general rule. Thanks
