### ISSUE TITLE
Unable to return to call in progress after clicking phone's back button

### ISSUE THREAD

**Issue by judge2b** [SimpleMobileTools/Simple-Dialer#81] opened 2020-07-27 19:16 UTC
I navigated away from a call in progress by clicking the phone's "back" button and I had no way to get back to the call. I can reproduce this consistently. The notification that usually persists was not there, and reopening the app did not put me back in to the in-progress call. Since it was a conference line, the only way to cancel the call was to shut off my phone or go into airplane mode to get the call to hang up.

Environment:
Simple Dialer v5.4.1
Moto G7 Power (XT1955-5)
Android 9

**Comment by tibbi** [comment] 2020-08-07 20:43
starting from 5.5.0 if you exit the app the call will always end. Pressing the Home button will work as expected, it will just move the app in the background.

**Comment by 12people** [comment] 2020-08-08 09:02
I've had a similar problem, and I'm not sure how to reproduce it.
I was on the lock screen when I received a call (might have clicked back — I don't remember) and after unlocking my phone, there was no screen or notification to pick up the call from. Just the ringtone playing.
Does the fix in 5.5.0 solve issues before the call is picked up too?

**Comment by tibbi** [comment] 2020-08-08 11:00
no, that is a different thing

**Comment by oonet** [comment] 2020-09-21 23:25
Simple Dialer 5.5.0

Hitting back button in call hangs up (intending to go back to previous screen within Simple Dialer).

While on a call, hit home button to go to home screen. Works as expected.
Click Simple Dialer icon to return to call. Dialer behaves as if no call in progress.
Make a new call without hanging up on old call. Dialer jams further.

Also, after going to home screen during call, turn screen off. Then turn on. Login. screen cycles off and on by itself.

**Comment by tibbi** [comment] 2021-07-25 19:10
duplicate of #104

**Closed by tibbi** 2021-07-25 19:10 UTC
Labels: bug
