### ISSUE TITLE
Feature Request: Option for Persistent Voice Mail Notification

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Dialer#38] opened 2020-05-25 23:56 UTC
I accidentally dismissed the voice-mail notification and was unable to recall it until after a device reboot.

**Comment by tibbi** [comment] 2020-05-26 07:36
duplicate of #23

**Closed by tibbi** 2020-05-26 07:36 UTC

**Comment by Saijin-Naib** [comment] 2020-05-26 13:23
Are the in-call and voice mail waiting both the same?

**Comment by tibbi** [comment] 2020-05-26 13:46
I dont know, not really differentiating between any of those

**Comment by Saijin-Naib** [comment] 2020-05-26 13:56
Issue #23 is about the in-call (you actually having an open phone call), and this issue is about your voicemail notification (not being in a call).
