### ISSUE TITLE
block calls from numbers that are not in the contact list

### ISSUE THREAD

**Issue by lucamp** [SimpleMobileTools/Simple-Dialer#324] opened 2022-03-23 18:53 UTC
Hi,
as a drastic measure to fight unwanted calls on some specific scenario (such as when you are on vacation), it would be nice to have an option that block calls from numbers that are not in the contact list.

Thanks

**Comment by tibbi** [comment] 2022-03-23 19:14
duplicate of #146

**Closed by tibbi** 2022-03-23 19:14 UTC
