### ISSUE TITLE
no missed calls notification

### ISSUE THREAD

**Issue by Jumbo125** [SimpleMobileTools/Simple-Dialer#701] opened 2023-10-05 21:53 UTC
Hello Tibbi

I would like to ask you about the problem: missed notification.

If i forgot my smartphone and i get an incoming call, i can't see any notification. 
Normally the dialer shows a notification on the lock screen. I activated the function "App symbol indicator". It don't work......
I set the simple dialer as default app.
The factory dialer app is on the device too. I don't have root permissions, so i can only set it as "not-default" dialer.

if i have a missed incall, the factory dialer shows a notifiaction on the lockscreen. (its not so good)
is there any soultion?

i read in some other posts, that the problem isn't new.
You wrote on each posts, that you can't do anything, becuase the missed call notification is a system setting......

But i tried some other dialer apps, and they show a notification about missed calls and the also use the app symbol indicator.....
do you have a idea?

if i go in the factory app setting -> notification -> i have the category missed call notification.
if i go in the simple dialer app settings -> notification -> i only have the categroies call_notification_channel and call_notification_channel_history

my phone:
Samsung Galaxy S9
Android 10

thank you a lot

**Comment by Aga-C** [comment] 2023-10-06 05:28
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/5'

**Comment by Aga-C** [comment] 2023-10-06 05:29
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/5.

**Closed** 2023-10-06 07:32 UTC
