### ISSUE TITLE
call blocking with wildcard

### ISSUE THREAD

**Issue by DIY-Blub** [SimpleMobileTools/Simple-Dialer#376] opened 2022-06-15 11:30 UTC
Unfortunately, the "Mange blocked numbers" do not work as wildcard. Entering +493* should block all +493xxxxx numbers. This is very important because of (daily) scam calls with different numbers, but always starting with +493...

**Comment by tibbi** [comment] 2022-06-15 12:19
duplicate of #82

**Closed by tibbi** 2022-06-15 12:19 UTC
