### ISSUE TITLE
Calling emergency services fails (UK)

### ISSUE THREAD

**Issue by vithusel** [SimpleMobileTools/Simple-Dialer#493] opened 2022-12-02 22:49 UTC
I do not wish to recreate the issue.

However can grab logs.

Call errors but doesnt connect. I did get a call back from emergency services so it seems a connection is made then aborted.

I am based in the UK, Using Dual Sim

**Comment by Aga-C** [comment] 2022-12-03 08:14
Probably it's the same as https://github.com/SimpleMobileTools/Simple-Dialer/issues/158.

**Comment by tibbi** [comment] 2022-12-03 08:35
yep, duplicate of #158

**Closed by tibbi** 2022-12-03 08:35 UTC
Labels: bug
