### ISSUE TITLE
[Feature Request] Block International Country Codes

### ISSUE THREAD

**Issue by DepecheCodeInstitute** [SimpleMobileTools/Simple-Dialer#259] opened 2021-11-09 18:53 UTC
Hi there, 

Love your work! I've been getting a few pesky spam calls lately, all from international country codes, and just realised that it would be super neat if I could choose to block incoming international calls, particularly if I were able to set up exceptions (i.e block all International callers, except for two countries etc)

Thank you for your time, keep up the smashing work :)

**Comment by tibbi** [comment] 2021-11-09 20:17
duplicate of #82

**Closed by tibbi** 2021-11-09 20:17 UTC
