### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by subhashis-barad** [SimpleMobileTools/Simple-Dialer#597] opened 2023-05-01 13:30 UTC
Adding a call recording would be wonderful,
I was using DIaler,Messages and contacts from ricedroid apps, but I switched to simple dialer, msgs and contacts because of this UI and features. But one thing I miss is a call recording option.

thanks for making this app, this is so so so awesome and cool looking

**Comment by Sureshgorai25** [comment] 2023-05-01 14:23
> Adding a call recording would be wonderful, I was using DIaler,Messages and contacts from ricedroid apps, but I switched to simple dialer, msgs and contacts because of this UI and features. But one thing I miss is a call recording option.
> 
> thanks for making this app, this is so so so awesome and cool looking

Same for me

**Comment by Aga-C** [comment] 2023-05-01 14:48
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/36.

**Closed** 2023-05-01 17:39 UTC
