### ISSUE TITLE
Show time of call in Call Log

### ISSUE THREAD

**Issue by lfriese** [SimpleMobileTools/Simple-Dialer#201] opened 2021-07-17 11:28 UTC
FR: It would be very handy to show the time at which a call has started in the Call Log. Currently, only the date is shown, except for groups of calls (having called the same number multiple times), where you have the option "Show Grouped Calls" and have the time of each call displayed in the popup window.

It would be great if you could implement any option to see the time at which a (single) call took place. Thanks a lot!

Sincerely,
l_friese

**Comment by tibbi** [comment] 2021-07-17 12:09
duplicate of #147

**Closed by tibbi** 2021-07-17 12:09 UTC
