### ISSUE TITLE
(Feature request) option show contact thumbnails

### ISSUE THREAD

**Issue by Charles7z** [SimpleMobileTools/Simple-Dialer#679] opened 2023-08-30 17:02 UTC
Simple mobile tools contact app has the option to show or not show the thumbnails of contacts but this feature is absent in the other simple mobile tools apps that contacts interacts with — the dialer and sms messages — which makes it a little disjointed.

**Comment by Aga-C** [comment] 2023-08-30 17:25
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/421.

**Closed** 2023-08-30 19:02 UTC
