### ISSUE TITLE
Unable to set app language to English when primary system language is not English

### ISSUE THREAD

**Issue by r3-l5-r3** [SimpleMobileTools/Simple-Dialer#689] opened 2023-09-12 21:31 UTC
**Device app version:** 5.18.0
**Device Android version:** 13

When going to Settings via ⚙ > General > Language, English isn't displayed as an option in the list. *(see below image)*

![Screenshot_20230912-171216-lowres](https://github.com/SimpleMobileTools/Simple-Dialer/assets/22544090/d10df688-5b8e-481e-aeb6-1c8a722f4c71)

**Comment by Aga-C** [comment] 2023-09-13 04:48
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2864.

**Comment by tibbi** [comment] 2023-09-13 08:13
will be added after app update

**Closed by tibbi** 2023-09-13 08:13 UTC
