### ISSUE TITLE
Add a way to disable dialog to select app when calling

### ISSUE THREAD

**Issue by Tanmandal** [SimpleMobileTools/Simple-Dialer#535] opened 2023-02-09 05:43 UTC
When simple dialer is not set as default 
While making a call a dialog appears everytime asking for which app to call from please add a way to disable the dialog (complete action using) and directly call from the system dialer

Given screenshot for better understanding
![Screenshot_2023-02-09-11-08-33-814-edit_android](https://user-images.githubusercontent.com/93572359/217727945-b951757a-1dcb-4862-bafa-a90340a00786.jpg)

**Comment by tibbi** [comment] 2023-02-09 08:20
that is handled by the system, not us. Can you set other downloaded dialer apps as the default one?

**Comment by tibbi** [comment] 2023-02-09 15:41
actually, duplicate of #530

**Closed by tibbi** 2023-02-09 15:41 UTC

**Comment by Tanmandal** [comment] 2023-02-09 18:58
> default

Yes I can set other downloaded apps as default caller

**Comment by Tanmandal** [comment] 2023-02-09 19:29
I have a suggestion that add a toggle in the settings which would make your app not identify itself as a phone app that would fix the issue
