### ISSUE TITLE
Incoming call screen is displayed "underneath the fingerprint scanner UI"

### ISSUE THREAD

**Issue by mijorus** [SimpleMobileTools/Simple-Dialer#600] opened 2023-05-08 08:51 UTC
I have a nothing phone 1. I can't simply reply to an incoming call when the phone is locked, because the fingerprint scanner UI is displayed on top of the incoming call UI.

Other dialer apps don't have this problem

**Comment by tibbi** [comment] 2023-05-08 10:11
duplicate of #574

**Closed** 2023-05-08 10:11 UTC

**Comment by mijorus** [comment] 2023-10-26 12:50
Hi @tibbi , this is still not fixed for me.
Nothing phone 1, android 13.
