### ISSUE TITLE
Feature request: Add option to send SMS in the incoming call screen

### ISSUE THREAD

**Issue by heiwiper** [SimpleMobileTools/Simple-Dialer#349] opened 2022-05-17 15:16 UTC
It would be nice to have a feature where you could directly reply to an incoming call with an SMS like "I will call you later", for example there could be a button or swipe in the incoming call screen where the app would invoke the SMS app with the number of the caller so the user can directly start typing in his default SMS app.

**Comment by vanous** [comment] 2022-10-29 05:43
Much needed, but as for the issue tracker I suggest to close this as a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/42

**Comment by tibbi** [comment] 2022-10-29 07:07
duplicate of #42

**Closed by tibbi** 2022-10-29 07:07 UTC
Labels: feature request
