### ISSUE TITLE
Persistent notification after hang up

### ISSUE THREAD

**Issue by tb06** [SimpleMobileTools/Simple-Dialer#326] opened 2022-04-06 21:07 UTC
Hello:

Sometimes, after a call, a persistent notification remains, telling that the call is finished, and the only way to close the notification is to kill the dialer app (pressing the red phone button doesn't do anything, nor pressing the notification itself):

![image](https://user-images.githubusercontent.com/51849819/162070521-e8536b30-d939-4c8a-96e8-acaaff94637a.png)

I didn't identify why it happens sometimes and not after other calls :-/.

**Comment by tibbi** [comment] 2022-04-06 21:12
what app and OS version are you using? Is that a rooted device?

**Comment by tb06** [comment] 2022-04-07 05:17
App version: 5.11.5
OS version: Android 10
This is a non-rooted device

**Comment by lipici** [comment] 2022-04-21 06:48
Last version of sinple dialler
Android 11 non rooted
I can confirm, if you click on misssed call dosent erase.

**Comment by tb06** [comment] 2022-05-02 20:05
> Last version of sinple dialler Android 11 non rooted I can confirm, if you click on misssed call dosent erase.

In my case it's not a missed call but an answered call ;-)

**Comment by lipici** [comment] 2022-05-03 01:29
That too, if someone calls you while you are in anotjer call.

You need to force close the app or more simple to activate airplane mode and then turn it off.

**Comment by tb06** [comment] 2022-07-20 07:06
> > Last version of sinple dialler Android 11 non rooted I can confirm, if you click on misssed call dosent erase.
> 
> In my case it's not a missed call but an answered call ;-)

And it happens even with some outgoing calls.
(Issue still there in version 5.13.3 of the app.)

**Comment by RadRussianRus** [comment] 2022-07-25 07:40
Same problem here.
App version: 5.13.3
Android 8.1.0 (no root)

**Comment by sebasarena** [comment] 2022-08-05 13:04
Same problem, with answered calls.

App version 5.14.0
Android 11 (no root).

**Comment by sebasarena** [comment] 2022-10-12 01:20
Still the same problem with answered calls.

App version 5.15.4
Android 11 (no root).

**Comment by sphh** [comment] 2022-10-12 06:50
I also sometimes get the persistent notification: It appears _after_ I ended the call. It does not appear every time I hang up, but it has appear on hanging up with any of these methods: `Stop call` button on screen, power button and using the control on the (wired) headphones.

App version 5.15.4
Android 8 (no root)

**Comment by sebasarena** [comment] 2022-10-13 13:25
> I also sometimes get the persistent notification: It appears _after_ I ended the call. It does not appear every time I hang up, but it has appear on hanging up with any of these methods: `Stop call` button on screen, power button and using the control on the (wired) headphones.
> 
> App version 5.15.4 Android 8 (no root)

Right. I forgot to specify the same that you mentioned: “It appears _after_ I ended the call”. 

But in my particular case it appears **_every single time_** I hang up. It's disappointing and frustrating.

**Comment by tibbi** [comment] 2022-10-13 15:10
some exact steps for reproducing would be good. Like are you initiating the call? Do you move the app in background during the call, or the fullscreen view is always in the foreground, maybe even with screen on? Do you end the call with the top notification or that fullscreen view?

**Comment by sebasarena** [comment] 2022-10-13 16:09
> > Like are you initiating the call?
> 
> No difference.
> 
> > Do you move the app in background during the call, or the fullscreen view is always in the foreground,
> 
> I have the fullscreen view always in the foreground.
> 
> > maybe even with screen on?
> 
> On my phone the screen locks quickly and turns off (see also next question).

All of this happens exactly the same with my phone.

The only difference between “sphh” and myself is the last question:

“Do you end the call with the top notification or that fullscreen view?”

I always end up the call with the fullscreen view. The top notification button to hang up doesn't work at all in my phone.

**Comment by sphh** [comment] 2022-10-14 13:53
I now ended a couple of calls not from the full-screen view, but with the help of the top notification (the full-screen view was still in front and I swiped down from the top border and then pressed the red phone symbol): Every time I did this, the call was ended and the notification disappeared. But then the notification popped up again just to disappear after ½-1 second again.

**Comment by witneyman** [comment] 2022-10-14 14:14
Just to add that I also experience the Call Ended notification that cannot be closed. It seems to occur more frequently with certain numbers called. But I can't detect a pattern in its occuring.

**Comment by Naveen3Singh** [comment] 2022-10-17 18:54
<img src="https://user-images.githubusercontent.com/36371707/196258360-101835dd-59b4-4860-8b25-1e5d37d9e056.png" width=264 />

When this occurs, is the status text always "Call ended"? @tb06 @sebasarena @sphh @witneyman

**Comment by witneyman** [comment] 2022-10-18 08:00
It's usually 'Call ended' for me. But just occasionally it has shown 'Ongoing call even though the call has been ended. In either case the notification can not be cancelled

**Comment by sphh** [comment] 2022-10-18 09:45
I never see the "Call ended" but always the "Ongoing call" notification (which is worrying).

Clicking on the red phone does nothing as does swiping it away: You cannot get rid of that notification.

**Comment by tb06** [comment] 2022-10-18 17:11
> <img alt="" width="264" src="https://user-images.githubusercontent.com/36371707/196258360-101835dd-59b4-4860-8b25-1e5d37d9e056.png">
> 
> When this occurs, is the status text always "Call ended" in everyone's case? @tb06 @sebasarena @sphh @witneyman

Hello:

I made an outgoing call (to my voicemail) this evening and the issue occured when I hanged up with "Appel en cours" (French equivalent to "Ongoing call") as the message in the persistent notification. So a different situation than in my first post.

Thanks for your help!

**Comment by sebasarena** [comment] 2022-10-18 22:16
> I never see the "Call ended" but always the "Ongoing call" notification (which is worrying).
> 
> Clicking on the red phone does nothing as does swiping it away: You cannot get rid of that notification.

It happens exactly the same in my case.

**Comment by Naveen3Singh** [comment] 2022-10-19 18:42
@tb06 @sphh @witneyman 

I still can not reproduce this at will but after some debugging & testing, I may have a fix. I'm attaching two APKs here with the second one more likely to fix this bug:

fix 1: https://github.com/Naveen3Singh/Simple-Dialer/releases/download/untagged-9698a45df4969964ea42/dialer-fdroid-debug-notif-fix-1.apk

fix 2: https://github.com/Naveen3Singh/Simple-Dialer/releases/download/untagged-9698a45df4969964ea42/dialer-fdroid-debug-notif-fix-2.apk (this one is likely to work)

@sebasarena 
> ... in my particular case it appears every single time I hang up ...

In that case, if you are willing, you should be able to _deterministically_ test out the above fixes. 

Thanks

**Comment by witneyman** [comment] 2022-10-19 19:15
Sorry but these links are not working for me
Steve

**Comment by witneyman** [comment] 2022-10-19 19:26
Thanks. I’ll try version 2 first and report back once I’ve had a chance to see if it solves the problem
Steve
**********

**Comment by witneyman** [comment] 2022-10-20 08:33
The first call I tried with version 2 was successful - there was no notification after the call. I'll wait for more calls and report further

**Comment by sebasarena** [comment] 2022-10-20 12:08
> @sebasarena
> 
> > ... in my particular case it appears every single time I hang up ...
> 
> In that case, if you are willing, you should be able to _deterministically_ test out the above fixes.
> 
> Lemme know if it works or not. Thanks

I don't like very much using the beta version of apps, because they are usually more unstable.
But I'll think about installing this one, if it really works for everyone else.

Thanks again for all your hard work and for answering us so diligently!

**Comment by Naveen3Singh** [comment] 2022-10-20 12:48
>beta version

No need to keep using them indefinitely. The APK files I shared are only for testing the fix, you can (and should) uninstall them afterward. (Once related changes are merged, the issue will be fixed in the next release on google play and fdroid)

Thanks.

**Comment by sebasarena** [comment] 2022-10-20 13:29
> > beta version
> 
> No need to keep using them indefinitely. The APK files I shared are only for testing the fix, you can (and should) uninstall them afterward. (Once related changes are merged, the issue will be fixed in the next release on google play and fdroid)
> 
> Thanks.

Well, I didn't know that. Thanks for explaining it.

**Comment by witneyman** [comment] 2022-10-21 08:56
I've now tested version 2 with several calls and so far the persistent notification has not been seen. Looks hopeful!

**Closed** 2022-10-25 08:11 UTC
Labels: bug
