### ISSUE TITLE
feature request: block unknown/private numbers

### ISSUE THREAD

**Issue by foolioo** [SimpleMobileTools/Simple-Dialer#403] opened 2022-07-12 08:22 UTC
It would very helpful if Simple Dialer would have the functionality to Block unknown/private numbers, in the same spirit as [Google Phone, Galaxy Dialer and others](https://www.howtogeek.com/775028/how-to-block-unknown-numbers-on-android/).

It can be achieved by installing Google Phone app, change the settings there to block private numbers and then switch back to Simple Dialer. Yet, There is no need for other dialer/phone apps if Simple Dialer could support this feature.

Thanks.

**Comment by tibbi** [comment] 2022-07-31 13:05
you can already block calls from not stored contacts in the app settings

**Comment by tibbi** [comment] 2022-07-31 13:08
actually duplicate of #37

**Closed by tibbi** 2022-07-31 13:08 UTC
Labels: feature request
