### ISSUE TITLE
Number of missed calls doesn't update

### ISSUE THREAD

**Issue by moonshaadow** [SimpleMobileTools/Simple-Dialer#256] opened 2021-11-03 18:05 UTC
Hi there.
The number of missed calls is never reseted, and continues to increase days after days.
Nothing is helping: touching the notification, opening the app, restarting the app or the phone, calling back the missed calls...

The notification disappears when touching it (this is expected behavior), but the number is still increased. 

Up-to-date app
Android 11

**Comment by tibbi** [comment] 2021-11-03 18:39
can you send a screenshot of what you mean? Arent you using some custom ROM?

**Comment by lipici** [comment] 2021-11-21 03:07
I have the same issue. Stock android.

**Comment by tb06** [comment] 2021-11-30 08:57
Hello:
I don't know if it's exactly what @moonshaadow was talking about but I don't know exactly how to "discharge" the missed calls counter.
My guess is that the only way to do it is to call back (with the other person answering) or to answer a new incoming call from the same person. But I'm not completely sure about that - I don't want to call back or to be called again by some of them ;-) .
Until you do that, the call is still marked as "missed call" and the counter accumulate all the missed calls in the notification that appears when a new call is not answered or when you restart the phone.
I can do more tests and/or send you screenshots if it helps.

**Comment by moonshaadow** [comment] 2021-11-30 12:09
Yes it is the same issue I'm talking about. Sometimes the counter is reset, but with no particular action. Calling back missed calls doesn't seem to be enough to reset the counter.

**Comment by Aga-C** [comment] 2021-11-30 12:32
Since these notifications are handling by the system, the best solution would be handling them by the Simple Dialer. But this is not an easy feature to add. 
Here is the related issue: https://github.com/SimpleMobileTools/Simple-Dialer/issues/5

**Comment by maze88** [comment] 2021-12-14 17:14
I am experiencing this issue too. Attaching a screensott, as requested by @tibbi.

![Screenshot_20211214-122127](https://user-images.githubusercontent.com/16841581/146046351-bf5c0a7e-97f1-4ec2-a33b-61d7a882b7e4.png)

Simple-dialer version: 5.11.1
Phone: Pixel 4a
Android: 12 (build SP1A.211105.002)

**Comment by nicolasGrim** [comment] 2021-12-23 11:19
Yes, I'm having the same issue, and it looks like it's been unresolved for quite a long time. I'm on a OnePlus Nord ce, with the f-droid latest version, no custom ROM.
Is there anything planned about it in the future ? I must say that this is rather annoying, and it seems like a basic feature that the dialer should be able to handle. Or maybe there's another way to go passed this, such as manually resetting the count ?

**Comment by tibbi** [comment] 2021-12-23 13:58
I dont know what is causing it, it works just fine on my devices. Those notifications are created by the system, not us, so it might be some system specific issue.

**Comment by odmfl** [comment] 2022-01-07 10:39
hi, i did some research apparently If a default dialer does not implement
"android.telecom.action.SHOW_MISSED_CALLS_NOTIFICATION" receiver,
a missed call notification created by Telecom is shown, this is just what is currently happening in simple dialer.

Now i dont know how to implement it i leave you this link of this commit may be it can help you

https://github.com/TinkerBoard2-Android/packages-apps-Car-Dialer/commit/ea074a2f527d4b9b3b5fd5ceafadba83c8b8ef13

if you can implement "android.telecom.action.SHOW_MISSED_CALLS_NOTIFICATION" receiver
i think that the problem is solved, unfortunately there is not much documentation about it so it is difficult.
@Aga-C i noticed that you have made some interesting pull requests and they have been merged, can you see if you can solve with this information i gave?  Thanks in advance for everything and thanks for your work

**Comment by tibbi** [comment] 2022-01-07 12:40
I dont want to maintain those notiifcations myself, having the system do it properly would be good :)

**Comment by tibbi** [comment] 2022-02-06 21:23
Added something to clear the missed calls count for version 5.12.0. It doesnt always help in my case, not sure why... Seems like some system issue, I found other people reporting such things too. The counter counting up missed calls by 2 is some system messup too that happens to me aswell and even if I tried handling "android.telecom.action.SHOW_MISSED_CALLS_NOTIFICATION" myself, I get the missed call intent twice... So I would have to compare their timestamps or use some ugly hacks as I haven't seen any nice solution to it there either.

**Comment by odmfl** [comment] 2022-02-07 07:32
Does getting the call intent twice mean that you receive the notification both from the system and from the simple dialer?
If so, we are on the right track.

I remember trying to add to the manifest android.telecom.action.SHOW_MISSED_CALLS_NOTIFICATION receiver

and then I added those classes

MissedCallNotificationController.java 

Basically I did a test, I made a wrong copy and paste of that commit that I had sent you previously, but actually the notifications were no longer arriving anywhere neither on the dialer nor from the system, so what was wrong with mine absurd copy paste was just the MissedCallNotificationController.java class.  You should create another MissedCallNotificationController.kt class.

**Comment by tibbi** [comment] 2022-02-07 09:20
> Does getting the call intent twice mean that you receive the notification both from the system and from the simple dialer? If so, we are on the right track.

No, it doesnt. We aren't receiving it at all, the notification is fully handled by the system. I just did some texting with that receiver to see what is sent there and that itself receives it twice. That commit you sent has 600+ lines of handling that missed call notification, that definitely isn't something I'd like to go into.

**Comment by lipici** [comment] 2022-04-21 06:52
Still same problem with last version on android 11 non rooted.

**Comment by SimonTigo** [comment] 2022-05-10 10:50
Same here. I even deleted all the missed calls in my call log, and still when I have a missed call it shows the total number of missed calls I've had since app installation

**Comment by youphyun** [comment] 2022-05-27 16:53
I also have the same issue, Simple-Dialer version 5.12.0 from F-Droid with LineageOS (Android 11) - lineage_klte.
Somewhere else I read that you can't clear missing call notification. Google disabled access to this functionality to third party apps.

**Comment by Naveen3Singh** [comment] 2022-09-10 21:36
Hey everyone!

If you guys are willing to test out a possible fix, [here's an APK](https://github.com/Naveen3Singh/Simple-Dialer/releases/download/test_missed_call_counter/dialer-fdroid-debug.apk)

or

If you want to compile yourself, this is the branch: https://github.com/Naveen3Singh/Simple-Dialer/tree/callCounterFix

Lmk how it goes (especially if it doesn't work)

**Closed** 2022-09-11 09:02 UTC
