### ISSUE TITLE
Feature Request, is it possibale to add call wating/hold in the dailer?

### ISSUE THREAD

**Issue by incomingflyingbrick** [SimpleMobileTools/Simple-Dialer#291] opened 2022-01-04 03:00 UTC
Hi, is it possible to add call waiting or call holding feature?
if not , what could we do if we want to use call wating or holding feature.

**Comment by tibbi** [comment] 2022-01-04 08:34
duplicate of #148

**Closed by tibbi** 2022-01-04 08:34 UTC
