### ISSUE TITLE
Outgoing and incoming calls in dual SIM

### ISSUE THREAD

**Issue by Valdnet** [SimpleMobileTools/Simple-Dialer#231] opened 2021-09-17 13:46 UTC
Steps:

1. Select a contact.
2. Call from 2nd SIM.
3. End the conversation.

Steps:

1. Pick up the call from the 2nd SIM card.
2. End the conversation.

Always a call in history is shown as from the first SIM card.

![obraz](https://user-images.githubusercontent.com/47037905/133792939-8388dc0e-aac9-4a31-8024-c7136e4c15d1.png)

Device:
Huawei Dual SIM smartphone

Apps:
Android 10
Simple Dialer 5.9.0

**Comment by tibbi** [comment] 2021-09-17 15:34
do other downloaded apps show it well?

**Comment by Valdnet** [comment] 2021-09-17 16:05
Yes. The system application shows well.

**Comment by tibbi** [comment] 2021-09-17 17:13
I mean some really downloaded one, not preinstalled. Those work differently.

**Comment by Valdnet** [comment] 2021-09-17 18:51
> I mean some really downloaded one, not preinstalled.

Haven't found a good open source app so can't check the described issue on another app.

**Comment by vdbhb59** [comment] 2021-11-08 19:52
@Valdnet same here. I too am looking for a dual sim dialer and which gives option to select either upon call button or some way like QKSMS does by clicking the SIM number in sms window.

**Comment by octotherp** [comment] 2021-11-09 19:30
+1 
call history shows sim2 instead of an actual sim1
however, incoming call screen (with pick up / block choice) as well as dial up and in progress screens show correct sim number.

also, can you show sim name instead/in addition? the one than could be set up in settings, not the carrier name.

**Comment by nicolasGrim** [comment] 2021-12-02 08:30
> 

Yep, I've tried another dialer that showed the correct sim number on the call history

**Comment by Valdnet** [comment] 2021-12-02 08:42
@tibbi Problem confirmed by nicolasGrim 😉.

**Comment by tibbi** [comment] 2022-02-05 22:54
duplicate of #41

**Closed by tibbi** 2022-02-05 22:54 UTC
