### ISSUE TITLE
Dialer in-call notification doesn't disappear after call ends

### ISSUE THREAD

**Issue by GithubUser96** [SimpleMobileTools/Simple-Dialer#441] opened 2022-09-04 09:43 UTC
The bug occurs on Lineage OS 19 Android 12. Only with Simple Dialer. It can't be dismissed by swipe nor by pressing the end call action button. The app must be forced stopped for it to go away.

**Comment by tibbi** [comment] 2022-09-04 11:38
can you somehow reproduce it? Duplicate of #326

**Closed by tibbi** 2022-09-04 11:38 UTC
