### ISSUE TITLE
call log/ history always showing sim 2 icon 

### ISSUE THREAD

**Issue by jithin-kg** [SimpleMobileTools/Simple-Dialer#176] opened 2021-04-14 09:28 UTC
in call log / history tab call log is always displayed as sim 2 .
Value of **simID** in RecentsHelper.kt is **always 2** in dual sim device even if called with sim 1

**Comment by tibbi** [comment] 2021-04-14 16:32
do other Dialer apps show it well?

**Comment by jithin-kg** [comment] 2021-04-16 07:23
no, other apps shows accurately.

**Comment by tibbi** [comment] 2021-04-16 19:44
and how are your SIM cards identified then?

**Comment by Coolporteur** [comment] 2021-05-03 13:24
Hi, i have same problem with this app, only sim 2 display in call log even if called with sim 1 ...
I have Xiaomi note 9t 5G MIUI 12.0.6

**Comment by tibbi** [comment] 2021-05-22 14:36
retest if it will still be broken in 5.7.0. Or if you want to check out a test version even earlier, just let me know. Ideally at hello@simplemobiletools.com, it is easier to send files there.

**Comment by tibbi** [comment] 2021-05-22 20:40
duplicate of #41

**Closed by tibbi** 2021-05-22 20:40 UTC
