### ISSUE TITLE
Call log display wrong sim slot number

### ISSUE THREAD

**Issue by amalgame21** [SimpleMobileTools/Simple-Dialer#254] opened 2021-11-01 07:33 UTC
when receiving call of the number of sim card in slot 1, it display the sim card icon "2" in call history, which is very misleading.

just tested out other problem: no matter dialing out with sim slot 1 or 2, all call history showing the sim icon "2". misleading again

**Comment by tibbi** [comment] 2021-11-01 09:25
duplicate of #41

**Closed by tibbi** 2021-11-01 09:25 UTC
