### ISSUE TITLE
feature request: a "missed call" phone notification.

### ISSUE THREAD

**Issue by meximan** [SimpleMobileTools/Simple-Dialer#100] opened 2020-09-01 15:04 UTC
I would like to suggest the following feature: 

add a "missed call" phone notification.

**Comment by tibbi** [comment] 2020-09-01 17:47
it is handled by the system, I guess it is a duplicate of #5

**Closed by tibbi** 2020-09-01 17:47 UTC

**Comment by ltGuillaume** [comment] 2020-09-01 19:29
To be fair, it's not handled by the system: it's handled by the Dialer app bundled with the system, for which this app is advertised as being an alternative.

**Comment by ngrigoriev** [comment] 2021-03-31 13:09
I would second it as a feature request. There are apps on Android that, apparently, can display more visible missed call notifications. System notification works but this tiny icon at the top is simply not visible enough and it is 100x more important than the notifications from Facebook/Ring/ etc. Can it be Dialer's function to display more "intrusive" missing call notifications?
