### ISSUE TITLE
Tapping a name immediately dials a number, user cannot choose which one... 

### ISSUE THREAD

**Issue by archont00** [SimpleMobileTools/Simple-Dialer#71] opened 2020-07-02 18:27 UTC
In Dialer, tapping on a contact name with multiple numbers, the Dialer starts calling one of the available numbers (the last in the list?) and the user has no chance to choose, which should be dialed. 

A workaround is to open Simple Contacts and dial from there. (The shortcoming is that the call history is not available there.)

**Comment by tibbi** [comment] 2020-07-03 08:49
duplicate of #15

**Closed by tibbi** 2020-07-03 08:49 UTC
