### ISSUE TITLE
screen off while ringing 

### ISSUE THREAD

**Issue by baraa272** [SimpleMobileTools/Simple-Dialer#362] opened 2022-05-29 06:58 UTC
poco x3 pro miui 13.0.4 
1. draw over other apps allowed
2. show on lock screen allowed 
3. show notification on lock screen allowed 
4. no restrictions from battery saver 
5. autostart enabled 
6. all permissions given and allowed 
and still sometimes screen off while ringing 

Note : tried a clone app (i modified apk) with added permission (show on lock screen) and it works flawlessly but i guess you need to look at this

**Comment by tibbi** [comment] 2022-05-29 07:06
which permission you mean? Can you maybe create a PR then?

**Comment by baraa272** [comment] 2022-05-29 11:04
![Screenshot_2022-05-29-11-09-30-805_com applisto appcloneR](https://user-images.githubusercontent.com/32843097/170858667-71e81c7c-7e32-43b8-8213-daa82a8cc75a.jpg)
When I choose this option in app

**Comment by baraa272** [comment] 2022-05-29 11:05
I can upload the modified apk if you need to investigate

**Comment by tibbi** [comment] 2022-05-29 11:06
I mean in the code, what have you changed?

**Comment by baraa272** [comment] 2022-05-29 11:17
I dont know this application modify the apk as you options I showed you then repack apk for install

**Comment by tibbi** [comment] 2022-05-29 11:19
you said that you modified the app code and `added permission (show on lock screen)`, how have you done it?

**Comment by baraa272** [comment] 2022-05-29 11:22
I didn't modify the app code I just insert the apk of simple dialer Into this app (app cloner) and enabled this option (show on lock screen) in app cloner options and let the app cloner make another modified apk and I installed that 
The modified apk works all the time when ringing it shows the dialer UI normally unlike stock dialer app which sometimes ring while screen still off

**Comment by baraa272** [comment] 2022-05-29 11:24
https://files.catbox.moe/cyfuxm.apk 
Link to modified apk

**Comment by tibbi** [comment] 2022-05-29 16:07
and if you enable that option in the official Simple Dialer? That doesnt help?

**Comment by baraa272** [comment] 2022-05-29 16:27
Even if I have this as screenshot below 
![Screenshot_2022-05-29-19-26-06-098_com miui securitycenter](https://user-images.githubusercontent.com/32843097/170880533-85d3c00a-1dff-4981-9e4c-a7121bcafa0f.jpg)
Sometimes stock dialer work and sometimes screen ring while still off

**Comment by baraa272** [comment] 2022-05-29 16:29
With the modified apk from cloner app with that option enabled it works all the time so I suspect it have something to do with permissions and so I did the modified apk from cloner app so you can look inside that apk to figure out why this modified apk work all the time while stock dialer sometimes work sometimes not

**Comment by lipici** [comment] 2022-06-08 07:46
Nothing new ? I have same problem. I need to unlock with fod every time to answer phone.

**Comment by tibbi** [comment] 2022-06-08 07:49
5.13.0 just started rolling out, update whenever it becomes available

**Comment by baraa272** [comment] 2022-06-14 20:32
will do and get you updated

**Comment by lipici** [comment] 2022-06-15 17:00
At me its working, just tested with my wife.

**Comment by 20210213** [comment] 2022-06-17 07:37
I still have the same issue with the dialer 5.13.1 from f-droid on an Ulefone Armor X5 with Android 9: After a while having worked with other apps, the phone will ring when receiving an incoming call, but the screen remains dark. I need to manually turn the screen on, unlock by pin and start the dialer app to accept the call. Obviously the app is killed by Android and doesn't start again automatically when required. This also happens with other apps - like third parts TTS - on this phone which seems to keep the last two apps open only.

**Comment by lipici** [comment] 2022-06-17 08:51
Try to delete cache and system data from app before uninstalling and then install the  app again.

**Comment by baraa272** [comment] 2022-06-17 17:14
> Try to delete cache and system data from app before uninstalling and then install the app again.

sadly here still issue persists even with 5.13.1

**Comment by 20210213** [comment] 2022-07-03 13:45
> Try to delete cache and system data from app before uninstalling and then install the app again.
Done, and finally reconfigured the app after restarting the phone. Since then it has worked. THX!

**Comment by baraa272** [comment] 2022-07-09 16:32
if you want dev you can close the issue and can recommend change roms for anyone facing this problem since i flashed PixelOS 12.1 and i'm not suffering from this issue anymore because its aosp rom

**Comment by tibbi** [comment] 2022-07-09 18:42
well ye, Ill better close it as we will add some improvements in the next app version released soon, but not much else we can do on our side. Yesterday I was using Googles preinstalled Phone app and it didnt wake up my device either, those issues are caused by system restrictions.

**Closed by tibbi** 2022-07-09 18:42 UTC
