### ISSUE TITLE
No contacts synchronized

### ISSUE THREAD

**Issue by Aircan** [SimpleMobileTools/Simple-Dialer#714] opened 2023-10-24 12:32 UTC
The list of contacts is empty. Like so, there are no names displayed, when receiving a call.

Android Version: 14
App version: 5.1.18
OS: GrapheneOS

Contacts do get synced to the phone from a Nextcloud instance using DAVx5. The according contacts Apps still holds the contacts that have been synced.

**Comment by Aga-C** [comment] 2023-10-24 12:38
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/230.

**Closed** 2023-10-24 12:39 UTC
