### ISSUE TITLE
No option for bluetooth earphones

### ISSUE THREAD

**Issue by 4n0nym0u53** [SimpleMobileTools/Simple-Dialer#150] opened 2021-01-17 15:47 UTC
When I pick up a call while the phone is connected to my bluetooth earphones, the selected output is the earphones (not visibly seemed though), but if I switch to the loudspeaker, I have no option to switch back to the earphones, it'll only switch back to the phones built-in earpiece speaker.

Phone: OnePlus 8T
Model: KB2003
Android version: 11
OxygenOS version: 11.0.6.9.KB05BA
Earphones: OnePlus Bullets Wireless Z
Simple Dialer version: 5.6.1 (from F-Droid)

**Comment by tibbi** [comment] 2021-01-17 16:15
duplicate of #96

**Closed by tibbi** 2021-01-17 16:15 UTC

**Comment by 4n0nym0u53** [comment] 2021-01-17 23:27
It's not a duplicate. My problem isn't that I can't switch audio output, but when I switch away from my bluetooth earphones, I can't switch back to them, the loudspeaker button will just switch the output to the phone's earpiece.
